title: FHIRFLARE IG Toolkit
description: Helm chart for deploying the fhirflare-ig-toolkit application
remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-seo-tag

show_downloads: true
google_analytics:

markdown: kramdown
highlighter: rouge

github:
  repository_url: https://github.com/Sudo-JHare/FHIRFLARE-IG-Toolkit